version: "3.11"

services:
  frontend:
    build:
      context: ./src
    ports:
      - "13002:13002"
    expose:
      - 13002
    depends_on:
      - backend
      - neo4j
    networks:
      - app-network

  backend:
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - "13001:13001"
    expose:
      - 13001
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - app-network

  neo4j:
    image: neo4j:5.20.0
    ports:
      - "7474:7474" # Neo4j Browser
      - "7687:7687" # Bolt protocol
    environment:
      NEO4J_AUTH: neo4j/hello123 # Set initial password here
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes" # Accept Neo4j license agreement
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
